-- MySQL Script generated by MySQL Workbench
-- Sat May 16 19:27:11 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema m2lformations
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema m2lformations
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `m2lformations` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish2_ci ;
USE `m2lformations` ;

-- -----------------------------------------------------
-- Table `m2lformations`.`Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m2lformations`.`Utilisateur` (
  `idUtilisateur` INT NOT NULL AUTO_INCREMENT,
  `nomUtilisateur` VARCHAR(250) NULL,
  `prenomUtilisateur` VARCHAR(250) NULL,
  `emailUtilisateur` VARCHAR(250) NULL,
  `motpasseUtilisateur` VARCHAR(250) NULL,
  `statutUtilisateur` TINYINT NULL,
  PRIMARY KEY (`idUtilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `m2lformations`.`Formation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m2lformations`.`Formation` (
  `idFormation` INT NOT NULL AUTO_INCREMENT,
  `intituleFormation` VARCHAR(250) NULL,
  `dateDebutFormation` DATETIME NULL,
  `dateFinFormation` DATETIME NULL,
  `lieuFormation` VARCHAR(250) NULL,
  `prestataireFormation` VARCHAR(250) NULL,
  PRIMARY KEY (`idFormation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `m2lformations`.`Inscrire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m2lformations`.`Inscrire` (
  `Utilisateur_idUtilisateur` INT NOT NULL,
  `Formation_idFormation` INT NOT NULL,
  PRIMARY KEY (`Utilisateur_idUtilisateur`, `Formation_idFormation`),
  INDEX `fk_Utilisateur_has_Formation_Formation1_idx` (`Formation_idFormation` ASC),
  INDEX `fk_Utilisateur_has_Formation_Utilisateur_idx` (`Utilisateur_idUtilisateur` ASC),
  CONSTRAINT `fk_Utilisateur_has_Formation_Utilisateur`
    FOREIGN KEY (`Utilisateur_idUtilisateur`)
    REFERENCES `m2lformations`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utilisateur_has_Formation_Formation1`
    FOREIGN KEY (`Formation_idFormation`)
    REFERENCES `m2lformations`.`Formation` (`idFormation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
